namespace WSLCC.Core.Models;

public sealed record ContainerCreateOptions(
    string Name,
    string Image,
    IReadOnlyList<string> PortMappings,
    IReadOnlyList<string> EnvironmentVariables,
    IReadOnlyList<string> Volumes,
    bool AutoRemove,
    bool Detached,
    IReadOnlyList<string>? Command = null,
    IReadOnlyDictionary<string, string>? Labels = null,
    string? Cpus = null,
    string? Memory = null,
    string? Hostname = null,
    string? Workdir = null,
    string? User = null,
    string? Entrypoint = null,
    string? Network = null,
    string? StopSignal = null,
    string? StopTimeout = null,
    string? ShmSize = null,
    bool Gpus = false,
    string? Tmpfs = null,
    string? PullPolicy = null,
    string? HealthCommand = null,
    string? HealthInterval = null,
    string? HealthTimeout = null,
    string? HealthRetries = null,
    string? HealthStartPeriod = null,
    IReadOnlyList<string>? Dns = null,
    IReadOnlyList<string>? Ulimits = null);
